---
- name: Refresh pacman mirrors
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install inetutils for hostname
  pacman:
    name: inetutils
    state: present

- name: Set the hostname
  hostname:
    name: "{{ hostname }}"
  when: hostname is defined

- include_tasks: shell.yml
- include_tasks: packages.yml
- include_tasks: journal.yml
- include_tasks: ntp.yml

