---
- name: Make sure the NTP service is running
  systemd:
    state: started
    name: ntpd
  become: true
  tags:
    - ntp

- name: "Set timezone to {{ timezone }}"
  timezone:
    name: "{{ timezone }}"
  become: true
  when: "timezone is defined"
  tags:
    - ntp
